### PR TITLE
Fix undefined input values

### PR DESCRIPTION
**Pull request by chadhietala**

### CODE REVIEW

**Comment by chancancode** [comment]
Oops, wrong browser profile, that was me merging 😄 

I was confused about this earlier, what is the difference between `InputValuePropertyChangeList` and `InputValueAttributeChangeList`? I mean I know what they do differently, but when are each of those used?

**Comment by chancancode** [comment]
Hm I missed it earlier, can you test updating also?

**Comment by chadhietala** [comment]
Ah yes `InputValueAttributeChangeList` can go away it's effectively dead code. Will follow up with another PR.

**Comment by chancancode** [comment]
Basically following INUR

**Pull request merged**
