### PR TITLE
Test the build status

### PR DESCRIPTION
**Pull request by asakusuma**
This should pass the build since it's only changing the readme.

### CODE REVIEW

**Comment by chadhietala** [comment]
WAT

**Comment by asakusuma** [comment]
master is failing for me locally because of a typescript error. checking to see if the same thing happens in travis

**Comment by asakusuma** [comment]
build hasn't finished yet but it's already failed at the typescript check @krisselden @chadhietala @rwjblue

**Comment by asakusuma** [comment]
```
> tslint -s ./.vscode/tslint-formatters -t vscode ./packages/**/*.ts; tsc -p . --noEmit
packages/glimmer-object/tests/ember-mixin-method-test.ts(80,8): error TS2339: Property 'foo' does not exist on type '{}'.
```

**Pull request closed without merging**
